services:
  frontend:
    container_name: frontend
    
    # This tells Docker Compose to build the image using the Dockerfile
    # in the current directory (./frontend).
    build:
      context: .
      dockerfile: Dockerfile
      args:

      # Modify these with the actual URLs of the backend.
        - NG_APP_API_BASE_URL=http://localhost:8181/api    # CHANGE THIS IP AND PORT
        - NG_APP_API_AUTH_URL=http://localhost:8181/auth   # CHANGE THIS IP AND PORT

    # Maps port 8080 on your computer to port 80 inside the container.
    ports:
      - "8080:80"
      

    environment:
      # This variable will be passed to the Nginx container at runtime
      # Change these to reflect the desired backend host and port
      - BACKEND_HOST=localhost  # CHANGE THIS
      - BACKEND_PORT=8181             # CHANGE THIS
    # Ensures the container restarts automatically if it stops.
    restart: unless-stopped